version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=8081
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped